<?php


namespace zwarthoorn\eveapi;


use GuzzleHttp\ClientInterface;
use Swagger\Client\Eve\Api\BookmarksApi;
use Swagger\Client\Eve\Configuration;
use Swagger\Client\Eve\HeaderSelector;
use zwarthoorn\eveapi\Authentication\EveAuth;

class Bookmarks extends BookmarksApi
{
    /**
     * @var EveAuth
     */
    private $eveAuth;

    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $host_index = 0)
    {
        if ($config === null)
        {
            $this->eveAuth = new EveAuth();
            $config = new Configuration();
            $config->setAccessToken($this->eveAuth->makeAuthentication());
        }

        parent::__construct($client, $config, $selector, $host_index);
    }

    public function getCharactersCharacterIdBookmarks($character_id = null, $datasource = 'tranquility', $if_none_match = null, $page = 1, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        return parent::getCharactersCharacterIdBookmarks($character_id, $datasource, $if_none_match, $page, $token); // TODO: Change the autogenerated stub
    }

    public function getCharactersCharacterIdBookmarksFolders($character_id = null, $datasource = 'tranquility', $if_none_match = null, $page = 1, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        return parent::getCharactersCharacterIdBookmarksFolders($character_id, $datasource, $if_none_match, $page, $token); // TODO: Change the autogenerated stub
    }

}