<?php


namespace zwarthoorn\eveapi;


use GuzzleHttp\ClientInterface;
use Swagger\Client\Eve\Api\CalendarApi;
use Swagger\Client\Eve\ApiException;
use Swagger\Client\Eve\Configuration;
use Swagger\Client\Eve\HeaderSelector;
use Swagger\Client\Eve\Model\PutCharactersCharacterIdCalendarEventIdResponse;
use zwarthoorn\eveapi\Authentication\EveAuth;

class Calendar extends CalendarApi
{
    /**
     * @var EveAuth
     */
    private $eveAuth;

    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $host_index = 0)
    {
        if ($config === null)
        {
            $this->eveAuth = new EveAuth();
            $config = new Configuration();
            $config->setAccessToken($this->eveAuth->makeAuthentication());
        }

        parent::__construct($client, $config, $selector, $host_index);
    }

    public function getCharactersCharacterIdCalendar($character_id = null, $datasource = 'tranquility', $from_event = null, $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        try {
            return parent::getCharactersCharacterIdCalendar($character_id, $datasource, $from_event, $if_none_match, $token); // TODO: Change the autogenerated stub
        }catch (ApiException $exception)
        {
            dd($exception);
        }
    }

    public function getCharactersCharacterIdCalendarEventId($event_id, $character_id = null, $datasource = 'tranquility', $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        return parent::getCharactersCharacterIdCalendarEventId($character_id, $event_id, $datasource, $if_none_match, $token); // TODO: Change the autogenerated stub
    }

    public function getCharactersCharacterIdCalendarEventIdAttendees($event_id, $character_id = null, $datasource = 'tranquility', $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        return parent::getCharactersCharacterIdCalendarEventIdAttendees($character_id, $event_id, $datasource, $if_none_match, $token); // TODO: Change the autogenerated stub
    }

    public function putCharactersCharacterIdCalendarEventId($event_id, $response, $character_id = null, $datasource = 'tranquility', $token = null)
    {
        $charrespone = new PutCharactersCharacterIdCalendarEventIdResponse();
        if (!in_array($response, $charrespone->getResponseAllowableValues()))
        {
            throw new \Exception('there is not correct response speciefied');
        }
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        parent::putCharactersCharacterIdCalendarEventId($character_id, $event_id, $response, $datasource, $token); // TODO: Change the autogenerated stub
    }

}