<?php


namespace zwarthoorn\eveapi;


use GuzzleHttp\ClientInterface;
use Swagger\Client\Eve\Api\ClonesApi;
use Swagger\Client\Eve\Configuration;
use Swagger\Client\Eve\HeaderSelector;
use zwarthoorn\eveapi\Authentication\EveAuth;

class Clones extends ClonesApi
{

    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $host_index = 0)
    {
        if ($config === null)
        {
            $this->eveAuth = new EveAuth();
            $config = new Configuration();
            $config->setAccessToken($this->eveAuth->makeAuthentication());
        }

        parent::__construct($client, $config, $selector, $host_index);
    }

    public function getCharactersCharacterIdClones($character_id, $datasource = 'tranquility', $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        return parent::getCharactersCharacterIdClones($character_id, $datasource, $if_none_match, $token); // TODO: Change the autogenerated stub
    }

    public function getCharactersCharacterIdImplants($character_id, $datasource = 'tranquility', $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        return parent::getCharactersCharacterIdImplants($character_id, $datasource, $if_none_match, $token); // TODO: Change the autogenerated stub
    }

}