<?php


namespace zwarthoorn\eveapi;


use GuzzleHttp\ClientInterface;
use Swagger\Client\Eve\Api\ContactsApi;
use Swagger\Client\Eve\Configuration;
use Swagger\Client\Eve\HeaderSelector;
use zwarthoorn\eveapi\Authentication\EveAuth;

class Contacts extends ContactsApi
{

    /**
     * @var EveAuth
     */
    private $eveAutch;

    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $host_index = 0)
    {
        if ($config === null)
        {
            $this->eveAutch = new EveAuth();
            $config = new Configuration();
            $config->setAccessToken($this->eveAuth->makeAuthentication());
        }

        parent::__construct($client, $config, $selector, $host_index);
    }


    public function deleteCharactersCharacterIdContacts($contact_ids, $character_id = null, $datasource = 'tranquility', $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }

        parent::deleteCharactersCharacterIdContacts($character_id, $contact_ids, $datasource, $token); // TODO: Change the autogenerated stub
    }

    public function getCharactersCharacterIdContacts($character_id = null, $datasource = 'tranquility', $if_none_match = null, $page = 1, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        return parent::getCharactersCharacterIdContacts($character_id, $datasource, $if_none_match, $page, $token); // TODO: Change the autogenerated stub
    }

    public function getCharactersCharacterIdContactsLabels($character_id = null, $datasource = 'tranquility', $if_none_match = null, $token = null)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        return parent::getCharactersCharacterIdContactsLabels($character_id, $datasource, $if_none_match, $token); // TODO: Change the autogenerated stub
    }

    public function postCharactersCharacterIdContacts($standing, $contact_ids, $character_id = null,$datasource = 'tranquility', $label_ids = null, $token = null, $watched = false)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        return parent::postCharactersCharacterIdContacts($character_id, $standing, $contact_ids, $datasource, $label_ids, $token, $watched); // TODO: Change the autogenerated stub
    }

    public function putCharactersCharacterIdContacts($standing, $contact_ids, $character_id = null, $datasource = 'tranquility', $label_ids = null, $token = null, $watched = false)
    {
        if ($character_id === null)
        {
            $character_id = $this->eveAuth->getResourceOwner()->getId();
        }
        parent::putCharactersCharacterIdContacts($character_id, $standing, $contact_ids, $datasource, $label_ids, $token, $watched); // TODO: Change the autogenerated stub
    }

}